In [3]:
import sys
import os
import requests

sys.path.append(os.path.abspath(".."))

from supabase import create_client
import os
import pandas as pd
from dotenv import load_dotenv
from config import (
    APPT_NAME, # "Appointment"
    CATEGORY_NAME, # "Category"
    FEATURES_NAME, # "Features"
    FEEDBACK_NAME # "Feedback"
)

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_PUBLIC_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

### This table contains the appointments freshly extracted from a google sheet for a late predictor project

In [5]:
aapt_res = (
    supabase
    .table(APPT_NAME)
    .select("*")
    .execute()
)

appt_df = pd.DataFrame(aapt_res.data)

appt_df

,appt_id,date,meeting_time,arrived_time,meeting_location,meeting_lat,meeting_lon,category_id
0,45179a8f-3370-46ca-adb6-b816eb674e1d,2026-01-02,2026-01-02T03:00:00+00:00,2026-01-02T03:07:00+00:00,uncle kkm (bukit panjang),1.377073,103.764559,d401e20e-71b8-4ced-ba53-016bbe2b7ce3
1,4b27094d-bc71-4fd4-89c0-79410e61437a,2026-01-03,2026-01-03T01:15:00+00:00,2026-01-03T01:20:00+00:00,virtual,NaN,NaN,502f2da8-69c2-4d53-81e4-686954c20652
2,f38627a5-05c2-49ce-890d-52b30139d9e1,2026-01-06,2026-01-06T11:30:00+00:00,2026-01-06T12:05:00+00:00,bbdc,1.367094,103.750257,ab7ee7b7-c4b7-4dc5-ae71-f33785d74a1b
3,db84c31a-c505-4bd9-8aed-2ffed4f87b11,2026-01-08,2026-01-08T11:00:00+00:00,2026-01-08T11:48:00+00:00,raffles place,1.284434,103.849791,fec0fa6b-77f5-4304-a71e-4505b1a96467
4,f27a8b79-dee4-45e4-bc52-4f43b79808ed,2026-01-15,2026-01-15T11:00:00+00:00,NaN,imm,1.336120,103.747071,fec0fa6b-77f5-4304-a71e-4505b1a96467
5,5d65bb52-25f6-4f0d-82e3-e7111ab379e4,2026-01-23,2026-01-23T12:00:00+00:00,2026-01-23T13:00:00+00:00,cck,1.384942,103.744580,fec0fa6b-77f5-4304-a71e-4505b1a96467
6,b1fc0a21-d18d-419a-8d21-6ca365f31a82,2026-03-08,2026-03-08T01:20:00+00:00,2026-03-08T01:30:00+00:00,uncle kkm (bukit panjang),1.377073,103.764559,bc69185d-2ce8-4650-bb8e-105aa2eb167b
7,ed5c430e-b8c3-44c2-a8a7-05e9471d9e7c,2026-03-27,2026-03-27T12:00:00+00:00,2026-03-27T12:15:00+00:00,her house,NaN,NaN,fec0fa6b-77f5-4304-a71e-4505b1a96467
8,b1085ce1-8ea8-4ae1-bf60-41030af58054,2026-03-28,2026-03-28T07:00:00+00:00,2026-03-28T07:30:00+00:00,suntec,1.295264,103.858294,4ea1b39c-3be4-4cb8-9279-0befb9c030a8
9,c8390536-ba09-4a9d-9243-7f8805ce5a8f,2026-04-10,2026-04-10T10:30:00+00:00,2026-04-10T10:39:00+00:00,suntec,1.295264,103.858294,fec0fa6b-77f5-4304-a71e-4505b1a96467
10,7c33dc1f-615b-446f-b0cd-9f39ac4c8bcb,2026-04-17,2026-04-17T04:45:00+00:00,2026-04-17T04:58:00+00:00,uncle kkm (bukit panjang),1.377073,103.764559,d401e20e-71b8-4ced-ba53-016bbe2b7ce3
11,07606fc0-546f-49fc-bea3-9ed9dc3644bf,2026-04-28,2026-04-28T02:00:00+00:00,2026-04-28T02:17:00+00:00,jurong east mrt,1.333056,103.742401,d401e20e-71b8-4ced-ba53-016bbe2b7ce3
12,e3a4b895-ef71-45d5-aa3a-8bb7e3b827e4,2026-05-08,2026-05-08T11:00:00+00:00,2026-05-08T11:21:00+00:00,senja hawker centre,1.387082,103.760789,fec0fa6b-77f5-4304-a71e-4505b1a96467
13,92c7e95c-4fbc-43bd-913c-7002e6a15a92,2026-05-13,2026-05-13T01:45:00+00:00,2026-05-13T01:50:00+00:00,bukit panjang,1.378382,103.762465,bc69185d-2ce8-4650-bb8e-105aa2eb167b

### This table contains the categories of appointments

In [9]:
category_res = (
    supabase
    .table(CATEGORY_NAME)
    .select("*")
    .execute()
)

category_df = pd.DataFrame(category_res.data)

category_df

                            category_id          category
0  d401e20e-71b8-4ced-ba53-016bbe2b7ce3             lunch
1  502f2da8-69c2-4d53-81e4-686954c20652         apply job
2  ab7ee7b7-c4b7-4dc5-ae71-f33785d74a1b          exercise
3  fec0fa6b-77f5-4304-a71e-4505b1a96467     dinner/drinks
4  bc69185d-2ce8-4650-bb8e-105aa2eb167b         breakfast
5  4ea1b39c-3be4-4cb8-9279-0befb9c030a8  work/career fair
6  c5f63956-4656-47dc-a0be-ed9ee73dbb88            others

### This table contains the features that were used for model training and inferencing

In [6]:
feature_res = (
    supabase
    .table(FEATURES_NAME)
    .select("*")
    .execute()
)

feature_df = pd.DataFrame(feature_res.data)

feature_df

,feature_id,day_of_week,time_of_day,distance_km,category,late_duration_min,appt_id
0,5aeb0e77-0537-458b-8cc5-f981b68eb93e,4,morning,1.274747,lunch,7,45179a8f-3370-46ca-adb6-b816eb674e1d
1,6ba12fe8-6026-412b-ab9d-a4bd7b61a095,1,evening,1.773078,exercise,35,f38627a5-05c2-49ce-890d-52b30139d9e1
2,8630b86c-6c44-479c-a517-2c4355bd2317,3,evening,15.205063,dinner/drinks,48,db84c31a-c505-4bd9-8aed-2ffed4f87b11
3,e2b89eae-3151-43e9-afc8-6eaf85272197,4,evening,1.130494,dinner/drinks,60,5d65bb52-25f6-4f0d-82e3-e7111ab379e4
4,f1f405c4-6d8a-4fe0-a966-5d99dc079bb2,6,morning,1.274747,breakfast,10,b1fc0a21-d18d-419a-8d21-6ca365f31a82
5,348226c0-a4fc-4981-b724-cce92e80f25d,5,afternoon,15.077114,work/career fair,30,b1085ce1-8ea8-4ae1-bf60-41030af58054
6,b39d0966-c9ea-47d6-a9b8-9213709638a4,4,evening,15.077114,dinner/drinks,9,c8390536-ba09-4a9d-9243-7f8805ce5a8f
7,e7b501e6-af24-4432-a584-15fb82d01928,4,afternoon,1.274747,lunch,13,7c33dc1f-615b-446f-b0cd-9f39ac4c8bcb
8,32177a6d-c394-4a0c-9e86-aa3ad6c2318e,1,morning,5.656470,lunch,17,07606fc0-546f-49fc-bea3-9ed9dc3644bf
9,8091c284-0de0-42ab-a12a-d002d0ebdf15,4,evening,0.871136,dinner/drinks,21,e3a4b895-ef71-45d5-aa3a-8bb7e3b827e4
10,7a046f84-6442-4139-9fd2-3a7603c8e07c,2,morning,1.001013,breakfast,5,92c7e95c-4fbc-43bd-913c-7002e6a15a92

### This table contains the feedback data provided by users after inferencing was made

In [7]:
feedback_res = (
    supabase
    .table(FEEDBACK_NAME)
    .select("*")
    .execute()
)

feedback_df = pd.DataFrame(feedback_res.data)

feedback_df

,feedback_id,created_at,pred_min,models_used,f_reg_id,meeting_location,date,meeting_time,arrived_time,meeting_lat,meeting_lon,category_id
0,1d7e19cd-c5ce-4d45-8285-30f7c8be2ad6,2026-05-13T18:50:23.842652+00:00,19,"random_forest, ridge",51eb9813-5efe-4bfa-b960-30338fb49bdc,Bukit Panjang Plaza,2026-05-06,2026-05-06T15:30:00+00:00,2026-05-06T18:30:00+00:00,1.35,103.9,4ea1b39c-3be4-4cb8-9279-0befb9c030a8
1,264926df-d08a-49d0-9f6d-57738c8283a6,2026-05-13T19:12:46.552824+00:00,19,"random_forest, ridge",51eb9813-5efe-4bfa-b960-30338fb49bdc,Bukit Panjang Plaza,2026-05-06,2026-05-06T15:30:00+00:00,2026-05-06T18:30:00+00:00,1.35,103.9,4ea1b39c-3be4-4cb8-9279-0befb9c030a8