In [1]:
import sys
import os
import requests

sys.path.append(os.path.abspath(".."))

In [2]:
from supabase import create_client
import os
import pandas as pd
from dotenv import load_dotenv
from config import (
    CLEAN_DATA_NAME, # "clean_data"
    FEATURE_STORE_NAME, # "feature_store"
    FEEDBACK_STORE_NAME # "feedback_store"
)

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_PUBLIC_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

### This table is the etl data freshly extracted from a google sheet for a late predictor project

In [3]:
clean_data_res = (
    supabase
    .table(CLEAN_DATA_NAME)
    .select("*")
    .execute()
)

clean_data_df = pd.DataFrame(clean_data_res.data)

clean_data_df

,id,date,meeting_time,arrived_time,meeting_location,category,meeting_lat,meeting_lon
0,38b0011a-628d-47e9-850a-fd788158500e,2026-01-02,2026-01-02T03:00:00+00:00,2026-01-02T03:07:00+00:00,uncle kkm (bukit panjang),lunch,1.377073,103.764559
1,a211d67d-f476-4ebd-8436-5b5e0f8e4da1,2026-01-03,2026-01-03T01:15:00+00:00,2026-01-03T01:20:00+00:00,virtual,apply job,NaN,NaN
2,8bcb133b-0b2f-4aad-9a4f-12c6298272c2,2026-01-06,2026-01-06T11:30:00+00:00,2026-01-06T12:05:00+00:00,bbdc,exercise,1.367094,103.750257
3,380366c4-3387-413d-846b-bdcb2485e2df,2026-01-08,2026-01-08T11:00:00+00:00,2026-01-08T11:48:00+00:00,raffles place,dinner/drinks,1.284434,103.849791
4,723ed175-4670-4ec1-b100-cef5864738aa,2026-01-15,2026-01-15T11:00:00+00:00,NaN,imm,dinner/drinks,1.336120,103.747071
5,b2347624-b998-4372-b013-b14284a4aab7,2026-01-23,2026-01-23T12:00:00+00:00,2026-01-23T13:00:00+00:00,cck,dinner/drinks,1.384942,103.744580
6,8c05f28f-86cd-447b-a92c-221109dbb06f,2026-03-08,2026-03-08T01:20:00+00:00,2026-03-08T01:30:00+00:00,uncle kkm (bukit panjang),breakfast,1.377073,103.764559
7,5caaa903-d0ab-42c8-ad51-bfa622e9c349,2026-03-27,2026-03-27T12:00:00+00:00,2026-03-27T12:15:00+00:00,her house,dinner/drinks,NaN,NaN
8,80678987-893e-4c21-89f1-0aa5be1c29b9,2026-03-28,2026-03-28T07:00:00+00:00,2026-03-28T07:30:00+00:00,suntec,work/career fair,1.295264,103.858294
9,5105371f-3197-423d-8279-381ea97ad68b,2026-04-10,2026-04-10T10:30:00+00:00,2026-04-10T10:39:00+00:00,suntec,dinner/drinks,1.295264,103.858294
10,d894c312-fa24-4eb2-9c12-0a8cdd5e96af,2026-04-17,2026-04-17T04:45:00+00:00,2026-04-17T04:58:00+00:00,uncle kkm (bukit panjang),lunch,1.377073,103.764559
11,21d74708-ebed-42d9-89dd-e49ce2d570da,2026-04-28,2026-04-28T02:00:00+00:00,2026-04-28T02:17:00+00:00,jurong east mrt,lunch,1.333056,103.742401
12,296ee358-f74c-42d4-8ab9-aa8e78fa6212,2026-05-08,2026-05-08T11:00:00+00:00,2026-05-08T11:21:00+00:00,senja hawker centre,dinner/drinks,1.387082,103.760789
13,217ba561-ebe6-49bf-adda-1f61611744ed,2026-05-13,2026-05-13T01:45:00+00:00,2026-05-13T01:50:00+00:00,bukit panjang,breakfast,1.378382,103.762465

### This table contains the feature store after processing the cleaned data

In [4]:
feature_store_res = (
    supabase
    .table(FEATURE_STORE_NAME)
    .select("*")
    .execute()
)

feature_store_df = pd.DataFrame(feature_store_res.data)

feature_store_df

Empty DataFrame
Columns: []
Index: []

### This table contains the feedback data provided by users after predictions has been made

In [6]:
feedback_store_res = (
    supabase
    .table(FEEDBACK_STORE_NAME)
    .select("*")
    .execute()
)

feedback_store_df = pd.DataFrame(feedback_store_res.data)

feedback_store_df

,id,created_at,pred_min,category,models_used,feature_registry_id,meeting_location,date,meeting_time,arrived_time,meeting_lat,meeting_lon
0,5c3aa608-37af-455f-b25b-db644357722e,2026-05-13T14:48:20.683371+00:00,19,dinner,"random_forest, ridge",8fd7d397-e3b6-4289-b5b0-3af28f89092f,Bukit Panjang Plaza,2026-05-06,2026-05-06T15:30:00+00:00,2026-05-06T18:30:00+00:00,1.35,103.9