In [1]:
import sys
import os
import requests

sys.path.append(os.path.abspath(".."))

In [ ]:
from supabase import create_client
import os
import pandas as pd
from dotenv import load_dotenv
from config import CLEAN_DATA_NAME, FEATURE_STORE_NAME

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_PUBLIC_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

In [ ]:
clean_data_res = (
    supabase
    .table(CLEAN_DATA_NAME)
    .select("*")
    .execute()
)

clean_data_df = pd.DataFrame(clean_data_res.data)

clean_data_df

,id,date,meeting_time,arrived_time,meeting_location,category
0,61e3967d-5ac3-40c7-a705-32532e91d0ab,2026-01-02,2026-01-02T03:00:00+00:00,2026-01-02T03:07:00+00:00,uncle kkm (bukit panjang),lunch
1,acf1fbc5-c2af-4338-8aae-3e50f8d355b1,2026-01-03,2026-01-03T01:15:00+00:00,2026-01-03T01:20:00+00:00,virtual,apply job
2,e8a229c1-fc50-46b2-827f-7af8b6e4227d,2026-01-06,2026-01-06T11:30:00+00:00,2026-01-06T12:05:00+00:00,bbdc,exercise
3,6521cabb-94e0-4e78-b3c5-e516801493d8,2026-01-08,2026-01-08T11:00:00+00:00,2026-01-08T11:48:00+00:00,raffles place,dinner/drinks
4,98c61721-136a-4168-b038-eac013bb2dea,2026-01-15,2026-01-15T11:00:00+00:00,NaN,imm,dinner/drinks
5,29cbacb1-029c-4140-bcc5-309953f2fd63,2026-01-23,2026-01-23T12:00:00+00:00,2026-01-23T13:00:00+00:00,cck,dinner/drinks
6,c337edd4-ed41-4e7d-9c8e-6f8384f27019,2026-03-08,2026-03-08T01:20:00+00:00,2026-03-08T01:30:00+00:00,uncle kkm (bukit panjang),breakfast
7,38b2639d-45ca-40f8-ad33-420f9bc2bf24,2026-03-27,2026-03-27T12:00:00+00:00,2026-03-27T12:15:00+00:00,her house,dinner/drinks
8,1643046c-18ff-4a6c-b3bc-532e9c4a7765,2026-03-28,2026-03-28T07:00:00+00:00,2026-03-28T07:30:00+00:00,suntec,work/career fair
9,79ecaf2b-c785-4806-9298-8e0f992536fa,2026-04-10,2026-04-10T10:30:00+00:00,2026-04-10T10:39:00+00:00,suntec,dinner/drinks
10,cf052a4c-c52e-4593-a746-bcfdba92385e,2026-04-17,2026-04-17T04:45:00+00:00,2026-04-17T04:58:00+00:00,uncle kkm (bukit panjang),lunch
11,f44e3f5a-b4de-4d48-a776-aa105a7c05ff,2026-04-28,2026-04-28T02:00:00+00:00,2026-04-28T02:17:00+00:00,jurong east mrt,lunch
12,0d977d80-6028-4e62-8f4c-0818e5d3213f,2026-08-05,2026-08-05T11:00:00+00:00,2026-08-05T11:21:00+00:00,senja hawker centre,dinner/drinks

In [13]:
feature_store_res = (
    supabase
    .table(FEATURE_STORE_NAME)
    .select("*")
    .execute()
)

feature_store_df = pd.DataFrame(feature_store_res.data)

feature_store_df

,id,day_of_week,distance_km,category,late_duration_min,time_of_day,clean_data_id
0,0a3eb301-d296-4af5-baf1-ff8d6f7800fd,4,1.274747,lunch,7,morning,61e3967d-5ac3-40c7-a705-32532e91d0ab
1,766eeda0-ef59-4cb6-8328-64f4f2b2e88d,1,1.773078,exercise,35,evening,e8a229c1-fc50-46b2-827f-7af8b6e4227d
2,7935d5f3-84ce-4b4c-8d54-d3e669d0a0d9,3,15.205063,dinner/drinks,48,evening,6521cabb-94e0-4e78-b3c5-e516801493d8
3,8c940c7c-9322-49d0-a627-77f7c2d22dfa,4,1.130494,dinner/drinks,60,evening,29cbacb1-029c-4140-bcc5-309953f2fd63
4,6e7bf174-c416-4aa8-b268-e9a5fed54163,6,1.274747,breakfast,10,morning,c337edd4-ed41-4e7d-9c8e-6f8384f27019
5,da67885f-d0c1-4e21-bc4e-e2729655b215,5,15.077114,work/career fair,30,afternoon,1643046c-18ff-4a6c-b3bc-532e9c4a7765
6,ef73f15d-574f-4e45-8167-fb40e6bedbf2,4,15.077114,dinner/drinks,9,evening,79ecaf2b-c785-4806-9298-8e0f992536fa
7,63121682-ac10-4c12-9223-a7396bc39023,4,1.274747,lunch,13,afternoon,cf052a4c-c52e-4593-a746-bcfdba92385e
8,64b9131e-792b-4842-9284-8c3611c591fa,1,5.656470,lunch,17,morning,f44e3f5a-b4de-4d48-a776-aa105a7c05ff
9,c77c57a4-75f8-4d98-8170-53e0aa947d8b,2,0.871136,dinner/drinks,21,evening,0d977d80-6028-4e62-8f4c-0818e5d3213f